# Generated by Django 4.1.1 on 2022-09-26 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(upload_to='Directors/')),
                ('born_place', models.CharField(max_length=100)),
                ('born_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.CharField(default='E01 - Serial Name', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(default='S01 - Serial Name', max_length=50)),
                ('number_episodes', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Episodes', models.ManyToManyField(default=None, to='web.episode')),
            ],
            options={
                'ordering': ['-season_name'],
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_name', models.CharField(max_length=200)),
                ('release_date', models.CharField(default='None', max_length=70)),
                ('end_date', models.CharField(default='None', max_length=70)),
                ('short_intro', models.TextField(max_length=700)),
                ('IMDb_RATING', models.CharField(default=None, max_length=50)),
                ('poster', models.ImageField(upload_to='Movie/Posters/')),
                ('summary', models.TextField(max_length=1600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(default='Russia', max_length=100)),
                ('time_minute', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(default='slug', null=True, unique=True)),
                ('age_rating_sys', models.CharField(choices=[('0', '0'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=100)),
                ('mpa_rating_sys', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=100)),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.director')),
                ('genre', models.ManyToManyField(to='web.genre')),
                ('seasons', models.ManyToManyField(default=None, to='web.season')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.CharField(default='None', max_length=70)),
                ('short_intro', models.TextField(max_length=700)),
                ('IMDb_RATING', models.CharField(default=None, max_length=50)),
                ('poster', models.ImageField(upload_to='Movie/Posters/')),
                ('summary', models.TextField(max_length=1600)),
                ('country', models.CharField(default='Russia', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('time_minute', models.PositiveIntegerField(default=1)),
                ('age_rating_sys', models.CharField(choices=[('0', '0'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=100)),
                ('mpa_rating_sys', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=100)),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.director')),
                ('genre', models.ManyToManyField(default=None, to='web.genre')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.movie')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='chose_season',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.season'),
        ),
    ]
