# Generated by Django 4.1.1 on 2022-09-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_favoriteserial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritemovie',
            old_name='movie',
            new_name='cinema_type',
        ),
        migrations.RenameField(
            model_name='favoriteserial',
            old_name='serial',
            new_name='cinema_type',
        ),
    ]
