# Generated by Django 4.1.1 on 2022-09-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_movie_country_alter_serial_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='number_episodes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
