# Generated by Django 4.1.1 on 2022-09-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_movie_favoritemovie_cinema_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='choose_favorite_later',
            field=models.CharField(choices=[('Later', 'Later'), ('Favorite', 'Favorite')], default='F', max_length=100),
        ),
        migrations.AddField(
            model_name='favoriteserial',
            name='choose_favorite_later',
            field=models.CharField(choices=[('Later', 'Later'), ('Favorite', 'Favorite')], default='F', max_length=100),
        ),
    ]
