# Generated by Django 4.1.1 on 2022-09-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_userratingmovie_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionswithmovie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actionswithserial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userratingmovie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
