# Generated by Django 4.1.1 on 2022-10-01 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0008_actionswithmovie_created_actionswithserial_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRatingSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('serial', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.serial')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
