# Generated by Django 4.1.1 on 2022-10-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_userreviewmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewmovie',
            name='text',
            field=models.TextField(max_length=2500),
        ),
    ]
