# Generated by Django 4.1.1 on 2022-10-06 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0013_alter_userreviewmovie_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviewSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('serial', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.serial')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
