# Generated by Django 4.1.1 on 2022-10-06 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_userreviewserial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersReviewLikeDislikeMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_dislike', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], max_length=100)),
                ('review', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.userreviewmovie')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
