# Generated by Django 4.1.1 on 2022-10-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_usersreviewlikedislikemovie_like_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='slug_field',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
