# Generated by Django 4.1.1 on 2022-10-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_director_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='genres',
            field=models.ManyToManyField(default=None, to='web.genre'),
        ),
        migrations.AddField(
            model_name='director',
            name='growth',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='born_date',
            field=models.DateTimeField(),
        ),
    ]
