# Generated by Django 4.1.1 on 2022-10-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_director_born_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='born_date',
            field=models.DateTimeField(),
        ),
    ]
